### ISSUE TITLE
PHP extensions disabled

### ISSUE THREAD

**Issue by finex** [peperoni60/drupal-docker#3]
Hi, I'm trying drupal-docker project but I've found an issue installing Drupal: the 'install.php' script returns an error on PHP extensions.

It looks that dom, SimpleXML and xml PHP extensions are not enabled.

The script doesn't install the related ubuntu packages and you've to install manually.

**Comment by finex** [comment]
I've extended the Dockerfile adding the php-xml,  and now the Drupal dependencies are met.
I've also added php-mbstring, php-json, php-imap, php-gd and php-curl like the drupal-vm project.

Thanks for sharing the drupal-docker code, I'm trying on a Linux environment and it looks promising.

**Comment by peperoni60** [comment]
Rebased the containers on Docker4Drupal.

**Comment by finex** [comment]
Thanks.
