### ISSUE TITLE
Linux vs Mac drupal-docker

### ISSUE THREAD

**Issue by apratt** [peperoni60/drupal-docker#4]
I was working on a blog ppost describing my journey as struggled to get Docker, Drupal and PHPStorm all working together when I stumbled across your work on drupal.org.

I work on Ubuntu so was quite surprised when I saw the README.md as Mac based. I rolled back to version 1 and am playing with that. It seems to me though that this should be two repositories or at least a clear branch depending on what you are trying to do.

**Comment by peperoni60** [comment]
Rebased on Docker4Drupal and removed all the Mac stuff.
